services:
  job-huntly-backend:
    image: huynguyen1911/job-huntly-backend:dev-latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - job-huntly-network

networks:
  job-huntly-network:
    name: job-huntly-network