spring:
  application:
    name: job-huntly-backend
  profiles:
    default: local
app:
  redis:
    enabled: ${APP_REDIS_ENABLED:true}

gemini:
  apiKey: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
  endpoint: https://generativelanguage.googleapis.com/v1beta/models/