spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_huntly_local?useSSL=false&allowPublicKeyRetrieval=true
    username: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      properties:
        hibernate:
          format-sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=