spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_huntly_local?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: codegym

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      properties:
        hibernate:
          format-sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect