spring:
  config:
    import: optional:file:.env.local.properties

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    database-platform: ${DB_DIALECT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


security:
  cors:
    allowed-origins: [ "http://localhost:3000" ]  # thêm domain FE khác nếu cần
    allow-credentials: true
  jwt:
    secret: ${JWT_SECRET}          # >= 32 ký tự
    expiry-seconds: 2592000        # 30 ngày
    issuer: "jobhuntly"
    cookie-name: "session"         # httpOnly cookie do BE set
    role-cookie-name: "role"

google:
  client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}

frontend:
  host: http://localhost:3000

backend:
  host: http://localhost:8080
  prefix: /api/v1