spring:
  config:
    import: optional:file:.env.local.properties
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  expiration: ${JWT_EXPIRATION:PT2H}
  secretKey: ${JWT_SECRET_KEY}

google:
  client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:${CLOUDINARY_NAME:}}
  api-key: ${CLOUDINARY_API_KEY:${CLOUDINARY_KEY:}}
  api-secret: ${CLOUDINARY_API_SECRET:${CLOUDINARY_SECRET:}}

frontend:
  host: http://localhost:3000

backend:
  host: ${BACKEND_HOST:http://localhost:8080}
  prefix: ${BACKEND_PREFIX:api/v1}

web:
  cors:
    allowed-origins:
      - "http://localhost:3000"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    exposed-headers:
      - "Authorization"
    allow-credentials: true
    max-age: 3600