spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_huntly_local?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: P@ssw0rd

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      properties:
        hibernate:
          format-sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: trongpro012847@gmail.com
    password: whue tbjz bela ezkd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

cloudinary:
  cloud-name: dsm6pgezz
  api-key: 152283123153368
  api-secret: F_cwTasxEU6MUvxQ_pqkbTLfFYE