spring:
  config:
    import: optional:file:.env.local.properties

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  data:
    redis:
      host: localhost
      port: 6379
#      password: redis
      timeout: 5s
    cache:
      type: redis
      redis:
        time-to-live: 10m
        key-prefix: 'jh::'
        use-key-prefix: true
        cache-null-values: false

  mail:
    host: smtp.zoho.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


security:
  cors:
    allowed-origins: [ "http://localhost:3000", "http://47.129.60.85:3000", "http://localhost:5173", "http://jobhuntly.io.vn", "https://jobhuntly.io.vn", http://admin.jobhuntly.io.vn", https://admin.jobhuntly.io.vn" ]  # thêm domain FE khác nếu cần
    allow-credentials: true
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiry-seconds: ${JWT_EXPIRATION:7200000}
    issuer: "jobhuntly"
    cookie-name: "access_token"         # httpOnly cookie do BE set
    cookie-domain: "jobhuntly.io.vn"

google:
  client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:${CLOUDINARY_NAME:}}
  api-key: ${CLOUDINARY_API_KEY:${CLOUDINARY_KEY:}}
  api-secret: ${CLOUDINARY_API_SECRET:${CLOUDINARY_SECRET:}}

frontend:
  host: ${FRONTEND_HOST}

backend:
  host: ${BACKEND_HOST:http://localhost:8080}
  prefix: ${BACKEND_PREFIX:api/v1}

# VNPay
vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  return-url: http://localhost:8080/api/v1/payments/vnpay/return
  tmn-code: ${VNPAY_TMN_CODE}
  secret-key: ${VNPAY_SECRET_KEY}
  version: "2.1.0"
  expire-minutes: 15

logging:
  level:
    com.jobhuntly.backend.vnpay: DEBUG
  host: ${BACKEND_HOST}
  prefix: ${BACKEND_PREFIX:/api/v1}

activation:
  ttl: PT5M
  resend-cooldown: PT2M

mail:
  imap:
    host: imap.gmail.com
    port: 993
    username: ${GMAIL_IMAP_USERNAME}
    password: ${GMAIL_IMAP_PASS}
    folder: INBOX
    poll-interval-ms: 30000
    mark-seen: true
    move-to-folder: Processed
    peek: true

  gmail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_IMAP_USERNAME}
    password: ${GMAIL_IMAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
