name: CI/CD - Jobhuntly Backend (dev)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: huynguyen1911
          password: dckr_pat_WXHIgr3YWPZu0_nCy17Vc9k6yMw

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: huynguyen1911/job-huntly-backend
          tags: |
            type=raw,value=dev-latest
            type=sha,format=long

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t huynguyen1911/job-huntly-backend:latest .
          docker push huynguyen1911/job-huntly-backend:latest

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Upload compose.yml lên EC2 (để ~/job-huntly-backend/compose.yml)
      - name: Upload docker-compose to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "compose.yml,.env"
          target: "~/job-huntly-backend/"

      # Ghi file .env trên EC2 từ GitHub Secrets
      - name: Write .env on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/job-huntly-backend
            cat > ~/job-huntly-backend/.env << 'EOF'
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            SPRING_JPA_DATABASE_PLATFORM=${{ secrets.SPRING_JPA_DATABASE_PLATFORM }}

            SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}

            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}

            APP_JWT_SECRET=${{ secrets.JWT_SECRET }}
            APP_JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}

            SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
            SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}

            BACKEND_HOST=${{ secrets.BACKEND_HOST }}
            BACKEND_PREFIX=/api/v1

            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}

            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            IMAGE_TAG=dev-latest
            EOF
            chmod 600 ~/job-huntly-backend/.env

      # Đăng nhập Docker Hub + Pull + Up -d
      - name: Deploy (pull & restart via docker compose)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            echo "Navigating to project directory..."
            cd ~/job-huntly-backend

            echo "Creating network (if not exists)..."
            echo "Currently, we re-use job-huntly-network..."
            docker network create job-huntly-network || true

            echo "Pulling latest image..."
            docker-compose -f compose.yml pull

            echo "Stopping old container if exists..."
            docker-compose -f compose.yml stop job-huntly-backend || true
            docker-compose -f compose.yml rm -f job-huntly-backend || true

            echo "Starting new container with correct name..."
            docker-compose -f compose.yml up -d --remove-orphans

            echo "Deployment completed!"